name: Container

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  test:
    name: Test building all images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build all images
        uses: docker/bake-action@v3.1.0
