name: Swift

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

env:
  SWIFT_COMMON_OPTIONS: --only-use-versions-from-resolved-file --skip-update

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/app/Dockerfile
          target: test
          push: false
          load: true
          cache-from: type=gha,scope=$GITHUB_REF_NAME-test
          cache-to: type=gha,mode=max,scope=$GITHUB_REF_NAME-test
          tags: miniblog/test:latest
      - name: Run tests
        run: docker run --rm miniblog/test:latest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: swift:${{ vars.DEFAULT_SWIFT_VERSION }}-jammy

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Resolve dependencies
        run: swift package resolve $SWIFT_COMMON_OPTIONS
      - name: Lint
        # The current version of the swift-format plugin requires listing the targets explicitly.
        # TODO: Remove explicit targets when/if the plugin automatically selects all targets.
        run: >-
          swift package $SWIFT_COMMON_OPTIONS plugin lint-source-code
            $(for target in $(ls Sources); do echo -n " --target $target"; done)
