name: Swift

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

env:
  default-swift-version: "5.8"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: [ {{ vars.default-swift-version }} ]
    container: swift:${{ matrix.swift-version }}-jammy

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Resolve dependencies
        run: swift package resolve --only-use-versions-from-resolved-file --skip-update
      - name: Build
        run: swift build --only-use-versions-from-resolved-file --skip-update --build-tests --jobs $(nproc --all)
      - name: Test
        run: swift test --only-use-versions-from-resolved-file --skip-update --parallel

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: swift:${{ vars.default-swift-version }}-jammy

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Lint
        # The current version of the plugin requires specifying every target.
        run: swift package --only-use-versions-from-resolved-file --skip-update plugin lint-source-code $(for target in $(ls Sources); do echo -n " --target $target"; done)
