name: Swift
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"
      - name: Resolve dependencies
        run: swift package resolve --only-use-versions-from-resolved-file --skip-update
      - name: Build
        run: swift build --only-use-versions-from-resolved-file --skip-update --build-tests --jobs $(nproc --all)
      - name: Test
        run: swift test --only-use-versions-from-resolved-file --skip-update --parallel
